### ISSUE TITLE
Release latest version of the fork

### ISSUE THREAD

**Issue by yanndinendal** [bpmn-io/snarkdown#6]
Hi @nikku, do you plan to release f39c834c06d34b95675e02288323588480fc819c?

We would be interested in the fix in #5 (or in developit/snarkdown#101) and are wondering if we need to make another fork. :)

**Comment by nikku** [comment]
Done with https://github.com/bpmn-io/snarkdown/commit/f489afd3fa0b19a287c8a1f6bdd3baf57765a821.
